development:
  clients:
    default:
      database: mysms_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
        max_pool_size: 5
        min_pool_size: 1
        wait_queue_timeout: 5000
        connect_timeout: 10
        socket_timeout: 10

test:
  clients:
    default:
      database: mysms_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
        max_pool_size: 1
        min_pool_size: 1
        wait_queue_timeout: 5000
        connect_timeout: 10
        socket_timeout: 10

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 1
        max_pool_size: 5
        min_pool_size: 1
        wait_queue_timeout: 5000
        connect_timeout: 10
        socket_timeout: 10
